name: Build and Push to Docker Hub, Deploy to GCP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Backend Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/my-api
          dockerfile: Dockerfile
          registry: docker.io
          tags: myapi-backend-latest, myapi-backend-${{ github.sha }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push the microservice
      - name: Build and push API Monitor Worker(Golang)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/my-api
          dockerfile: ./api-monitor-worker/Dockerfile
          registry: docker.io
          tags: myapi-microservice-latest, myapi-microservice-${{ github.sha }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy-to-gcp:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      
      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy myapi-backend \
            --image=${{ secrets.DOCKERHUB_USERNAME }}/my-api:myapi-backend-${{ github.sha }} \
            --platform=managed \
            --region=us-central1 \
            --set-env-vars="GITHUB_CLIENT_ID=${{ secrets.GIT_CLIENT_ID }},GITHUB_CLIENT_SECRET=${{ secrets.GIT_CLIENT_SECRET }},GITHUB_CALLBACK_URL=${{ secrets.GIT_CALLBACK_URL }},FRONTEND_URL=${{ secrets.FRONTEND_URL }},JWT_SECRET=${{ secrets.JWT_SECRET }},MONGODB_URI=${{ secrets.MONGODB_URI }},PORT=${{ secrets.PORT }}" \
            --allow-unauthenticated
      - name: Deploy Go microservice to Cloud Run
        run: |
          gcloud run deploy myapi-microservice \
            --image=${{ secrets.DOCKERHUB_USERNAME }}/my-api:myapi-microservice-${{ github.sha }} \
            --platform=managed \
            --region=us-central1 \
            --set-env-vars="MONGODB_URI=${{ secrets.MONGODB_URI }},DB_NAME=${{ secrets.DB_NAME }}" \
            --allow-unauthenticated